server:
  port: 8761
 
spring:
  application:
    name: EUREKA-SERVICE
 

 
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
        
